### ISSUE TITLE
Config.yaml changing

### ISSUE THREAD

**Issue by ETS5** [mikedmor/OctoPrint_MultiCam#15]
So i go to the config.yaml and change the stuff as shown
 multicam:
    _config_version: 1
    multicam_profiles:
    - URL: http://192.168.1.33/webcam/?action=stream
      isButtonEnabled: true
      name: Webcam 1
    - URL: http://192.168.1.33/webcam2/?action=stream
      isButtonEnabled: true
      name: Webcam 2
However when i go to the Octoprint web page and look up the multicam plugin and hit save it auto changes the config.yaml to this:
 multicam:
    _config_version: 1
    multicam_profiles:
    - URL: /webcam/?action=stream
      isButtonEnabled: true
      name: Webcam 1
    - URL: http://192.168.1.33/webcam2/?action=stream
      isButtonEnabled: true
      name: Webcam 2

Which makes it were i can not reach that camera outside of my network. 

Is there something I am missing that would change that if i hit the save button 

Because before i hit the save button it looks correct it has the http://192.168.1.42/webcam/?action=stream but once i hit the save button it removes the IP address part. Please help it is driving me nuts to constantly change the config.yaml file every time. 
![image](https://user-images.githubusercontent.com/35798060/68429535-e4388e80-0173-11ea-8ed7-cedfbe325a09.png)

**Comment by mikedmor** [comment]
Hey ETS5,

Its been a while since i last worked on this project, but if im remembering it correctly, the first cam is set using one of the default settings tabs in Octoprint (I believe it is called "Webcams & timelapse")

Once you make a change in that tab, the first camera option will automatically change to that new set location. If that does not work another thing you could try is adding a third webcam, and then setting its location to the one you are wanting to set.

Hopefully that helps.
