### ISSUE TITLE
Wrong button selected when returning to tab

### ISSUE THREAD

**Issue by OldCurmudgeon3DP** [mikedmor/OctoPrint_MultiCam#23]
I don't see a recent update in the files, but the behavior has changed this week. When I switch to the Control tab (only 2 cameras set up) the 2nd camera button is selected, but the primary camera feed is showing. I have to click the primary then the secondary to switch the feed.

Also if I switch tabs in the browser, when I return to Octoprint the primary feed is presented even if the secondary was selected. The secondary button is still selected though. This has been the case since I started using the plugin.

**Comment by StefanCohen** [comment]
Hi. I'm the author of the Dashboard plugin. The problem with the buttons is caused by the Dashboard and is tracked here: https://github.com/StefanCohen/OctoPrint-Dashboard/issues/174

I still haven't found a fix for the button problem but I'm working on it. The secondary problem you mentioned is as far as I understand not caused by the Dashboard.

**Comment by AbuMaia** [comment]
Hi Stefan. I am seeing this same problem with switching OctoPrint tabs and browser tabs and the camera feed changing, and I do *not* have Dashboard installed, so I doubt this is caused by Dashboard.

**Comment by radioburst** [comment]
I have the same issue and I also don't have Dashboard installed. I do however have [TabOrder](https://github.com/jneilliii/OctoPrint-TabOrder) installed maybe this causes the issue?
The problem occurs on Chrome and Firefox (Manjaro and macOS).

Are there any fixes available?

**Comment by mikedmor** [comment]
Fixed in version 0.4.0rc3
